first = int(input())
second = input()
third = first*int(second[2])
fourth = first*int(second[1])
fifth = first*int(second[0])
print(third)
print(fourth)
print(fifth)
print(fifth*100 + fourth*10 + third)